[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../api" }
anyhow = "1.0.86"
async-trait = "0.1.85"
chrono = "0.4.38"
gloo-net = "0.6.0"
mysql_async = "0.35.0"
paste = "1.0.11"
saphyr = "0.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.117"
async_cell = "0.2.2"
dashmap = "6.1.0"
tracing = "0.1.41"
toml = "0.8.20"
tokio = { version = "1.44.1", features = ["full"] }
image = "0.25.6"
blockhash = "1.0.0"
kamadak-exif = "0.6.1"
regex = "1.11.1"
ldap3 = { version = "0.11.5", features = ["tokio-rustls", "x509-parser"] }
sha2 = "0.10.8"
hex = "0.4.3"
