[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.85"
async_cell = "0.2.2"
chrono = "0.4.38"
gloo-net = "0.6.0"
mysql_async = "0.35.0"
paste = "1.0.11"
saphyr = "0.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.43.0", features = ["fs", "sync"] }
