[package]
name = "webapp"
version = "0.1.0"
authors = ["alex <no@reply>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api = { path = "../api" }
anyhow = "1.0.86"
dioxus = { version = "0.5", features = ["web"] }
dioxus-router = { version = "0.5.0", features = ["web"] }
gloo-console = "0.3.0"
gloo-net = "0.5.0"
gloo-storage = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.117"

# Debug
tracing = "0.1.40"
dioxus-logger = "0.5.0"
