[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace =  true }
gloo-net = { workspace =  true }
paste = { workspace =  true }
regex = { workspace =  true }
serde = { workspace =  true, features = ["derive"] }
